excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - plist

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length: 120
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
  warning: 40
  error: 50
  excluded: # excluded via string
    - iPhone
    - Session
    - EisenhowerTaskManager_UITests
variable_name:
  min_length: 2 # only min_length
  error: 4 # only error
  excluded: # excluded via string array
    - id
    - vc
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
