source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

def pods
    # Network
    pod 'Alamofire'
    pod 'SwiftyJSON'

    # SDK
    pod 'Firebase/Core'
    pod 'Firebase/Auth'

    # UI
    pod "TTGSnackbar"
end

target 'EisenhowerTaskManager-development' do
    pods
    pod 'SwiftLint' # Linter
    pod 'LicensePlist' # Libraries Licenses
end

target 'EisenhowerTaskManager-adhoc' do
    pods
end

target 'EisenhowerTaskManager-appstore' do
    pods
end

target 'EisenhowerTaskManagerTests' do
    pods
end
