source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

def pods
    # Network
    pod 'Alamofire'

    # SDK
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Performance'

    # UI
    pod 'TTGSnackbar'
    pod 'Eureka'
    pod 'DSGradientProgressView'
    pod 'GenericPasswordRow'

    # UX
    pod 'Haptica'

    # Extensions
    pod 'SwiftDate'
end

target 'EisenhowerTaskManager-development' do
    pods
    pod 'SwiftLint' # Linter
    pod 'LicensePlist' # Libraries Licenses
    pod 'SwiftGen' # Swift Generator
end

target 'EisenhowerTaskManager-adhoc' do
    pods

    # SDK - KPI/Beta/Crashlytics
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'EisenhowerTaskManager-appstore' do
    pods

    # SDK - KPI/Beta/Crashlytics
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'EisenhowerTaskManagerTests' do
    pods
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    if config.name == 'Release'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
    else
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
    end
  end
end
